/*package com.app.pojos;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

//This Table Must Already Be Populated and Generated by Developer
@Embeddable
public class ServicesOfVendor {
		int sov_id;						//auto generated 	-->	@Id
		String sov_name;      			//Added By Vendor	--> Checkboxes
		double sov_price;					//Added By Vendor 	--> Rs.500 
		
		
		
		public ServicesOfVendor() {
			System.out.println("In Default Service of vendor in client side pojo");
		}
	
		public ServicesOfVendor(int sov_id) {
			this.sov_id = sov_id;
		}
	
		public ServicesOfVendor(String sov_name, double sov_price) {
			super();
			this.sov_name = sov_name;
			this.sov_price = sov_price;
		}
		
		public ServicesOfVendor(int sov_id, String sov_name, double sov_price) {
			super();
			this.sov_id = sov_id;
			this.sov_name = sov_name;
			this.sov_price = sov_price;
		}


		@Id
		@GeneratedValue(strategy=GenerationType.IDENTITY)
		public int getSov_id() {
			return sov_id;
		}

		public void setSov_id(int sov_id) {
			this.sov_id = sov_id;
		}

		@Column(length=70)
		public String getSov_name() {
			return sov_name;
		}

		public void setSov_name(String sov_name) {
			this.sov_name = sov_name;
		}

		
		@Column(columnDefinition="double(7,2)")
		public double getSov_price() {
			return sov_price;
		}

		public void setSov_price(double sov_price) {
			this.sov_price = sov_price;
		}
			
		@Override
		public String toString() {
			return "ServicesOfVendor [sov_id=" + sov_id + ", sov_name=" + sov_name + ", sov_price=" + sov_price + "]";
		}


}

		
*/